// <auto-generated />
namespace IRRCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class set_person_martial_status_to_10_character : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(set_person_martial_status_to_10_character));
        
        string IMigrationMetadata.Id
        {
            get { return "201811160443182_set_person_martial_status_to_10_character"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
