// <auto-generated />
namespace IRRCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class after_delivery : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(after_delivery));
        
        string IMigrationMetadata.Id
        {
            get { return "201812060603231_after_delivery"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
