// <auto-generated />
namespace IRRCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_ResidetsCar_entity_model_class_with_one_to_many_relationship_to_Person_entity_class1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_ResidetsCar_entity_model_class_with_one_to_many_relationship_to_Person_entity_class1));
        
        string IMigrationMetadata.Id
        {
            get { return "201811200721343_added_ResidetsCar_entity_model_class_with_one_to_many_relationship_to_Person_entity_class1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
