// <auto-generated />
namespace IRRCMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class added_owner_column_to_the_Buildingunit_entity_Class_and_the_corresponding_Relationships : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_owner_column_to_the_Buildingunit_entity_Class_and_the_corresponding_Relationships));
        
        string IMigrationMetadata.Id
        {
            get { return "201811221006109_added_owner_column_to_the_Buildingunit_entity_Class_and_the_corresponding_Relationships"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
